### ISSUE TITLE
steps to install should be clearly defined iam getting errors while deploying app in windows 

### ISSUE THREAD

**Issue by tanve** [leecrossley/cordova-plugin-datetime-picker#9]
Severity    Code    Description Project File    Line
Error   CS0246  The type or namespace name 'NavigationOutTransition' could not be found (are you missing a using directive or an assembly reference?) [C:\XXXXXX\XXXX\platforms\wp8\XXXXX.csproj]   tgetharly   C:\tXXXXX\XXXXXX\Plugins\cordova-plugin-datetime-picker\DateTimePickerTask.cs   16

**Comment by leecrossley** [comment]
You need to install Microsoft.Phone.Controls.Toolkit and Coding4Fun.Toolkit.Controls, as mentioned in the README.
